[package]
name = "raytracing"
version = "0.1.0"
authors = ["Arjan de Pooter <mail@arjandepooter.nl>"]
edition = "2021"

[dependencies]
proptest = "1.4.0"
approx = "0.5.1"
image = "0.24.8"
anyhow = "1.0.79"