[package]
name = "raytracing"
version = "0.1.0"
authors = ["Arjan de Pooter <mail@arjandepooter.nl>"]
edition = "2021"

[dependencies]
proptest = "1.0.0"
approx = "0.5.0"
image = "0.23.14"
anyhow = "1.0.52"